app:
  - "src/lightning/app/**"
  - "src/lightning_app/*"
  - "tests/tests_app/**"
  - "tests/integrations_app/**"
  - "tests/integrations_app_examples/**"
  - "examples/app/**"
  - "docs/source-app/**"
  - "requirements/app/**"

pl:
  - "src/lightning/pytorch/**"
  - "src/pytorch_lightning/*"
  - "tests/tests_pytorch/**"
  - "tests/legacy/**"
  - "examples/pytorch/**"
  - "docs/source-pytorch/**"
  - "requirements/pytorch/**"

fabric:
  - "src/lightning/fabric/**"
  - "src/lightning_fabric/*"
  - "tests/tests_fabric/**"
  - "examples/fabric/**"
  - "docs/source-fabric/**"
  - "requirements/fabric/**"

ci:
  - ".actions/**"
  - ".azure/**"
  - ".github/**"
  - "dockers/**"
  - ".pre-commit-config.yml"

docs:
  - ".github/workflows/docs-build.yml"
  - "docs/**"
  - "requirements/docs.txt"
  - "requirements/*/docs.txt"

package:
  - ".github/workflows/ci-pkg-install.yml"
  - "setup.py"
  - "pyproject.toml"
  - "src/version.info"
  - "src/lightning/*/__setup__.py"
  - "src/lightning/*/__version__.py"
  - "src/lightning_app/*"
  - "src/lightning_fabric/*"
  - "src/pytorch_lightning/*"

dockers:
  - "dockers/**"
  - ".github/workflows/docker-build.yml"

dependencies:
  - "requirements.txt"
  - "requirements/**"
